In [122]:
import pandas as pd
import numpy as np


In [123]:
### METHODS:

### MAIN:
# Tested on:
#   1. skCrateLeft1.json -> works (dimensions match)
#   2. skCupRight1.json -> works (dimensions match)
#   3. skFloorRight.json -> works (dimension match + dimension same/numpy conversion)

contents = pd.read_json("/Users/kirillgugunishvili/Documents/GitHub/Project3-1/Data/SkeletonData/skCrateLeft1.json")
print(type(contents))
print()
display(contents)

<class 'pandas.core.frame.DataFrame'>



2023-11-22 11:54:38.059  \
timestamp     1700654078059222899   
body_list                      []   

                                     2023-11-22 11:54:38.159  \
timestamp                                1700654078159224899   
body_list  [{'position': [0.06269187480211201, 0.23638167...   

                                     2023-11-22 11:54:38.175  \
timestamp                                1700654078175975899   
body_list  [{'position': [0.061249434947967, 0.2368403375...   

                                     2023-11-22 11:54:38.192  \
timestamp                                1700654078192609899   
body_list  [{'position': [0.060380466282367005, 0.2371510...   

                                     2023-11-22 11:54:38.209  \
timestamp                                1700654078209228899   
body_list  [{'position': [0.059524856507778, 0.2371422499...   

                                     2023-11-22 11:54:38.225  \
timestamp                                1700654078225982899   
body_list  [{'position': [0.059154763817787004, 0.2367707...   

                                     2023-11-22 11:54:38.242  \
timestamp                                1700654078242618899   
body_list  [{'position': [0.060176365077495006, 0.2364491...   

                                     2023-11-22 11:54:38.259  \
timestamp                                1700654078259232899   
body_list  [{'position': [0.058992676436901, 0.2362396121...   

                                     2023-11-22 11:54:38.275  \
timestamp                                1700654078275982899   
body_list  [{'position': [0.060011230409145, 0.2360790520...   

                                     2023-11-22 11:54:38.292  ...  \
timestamp                                1700654078292628899  ...   
body_list  [{'position': [0.058555230498313, 0.2353321015...  ...   

                                     2023-11-22 11:54:43.793  \
timestamp                                1700654083793089899   
body_list  [{'position': [-0.18967261910438502, 0.2430174...   

                                     2023-11-22 11:54:43.809  \
timestamp                                1700654083809814899   
body_list  [{'position': [-0.188304513692855, 0.242877885...   

                                     2023-11-22 11:54:43.826  \
timestamp                                1700654083826319899   
body_list  [{'position': [-0.18694186210632302, 0.2426286...   

                                     2023-11-22 11:54:43.843  \
timestamp                                1700654083843071899   
body_list  [{'position': [-0.18561515212059002, 0.2422894...   

                                     2023-11-22 11:54:43.859  \
timestamp                                1700654083859820899   
body_list  [{'position': [-0.184339731931686, 0.242005527...   

                                     2023-11-22 11:54:43.876  \
timestamp                                1700654083876371899   
body_list  [{'position': [-0.182976365089416, 0.241660505...   

                                     2023-11-22 11:54:43.893  \
timestamp                                1700654083893091899   
body_list  [{'position': [-0.18166434764862002, 0.2411778...   

                                     2023-11-22 11:54:43.909  \
timestamp                                1700654083909824899   
body_list  [{'position': [-0.180418908596038, 0.240578994...   

                                     2023-11-22 11:54:43.926  \
timestamp                                1700654083926324899   
body_list  [{'position': [-0.17917568981647403, 0.2401091...   

                                     2023-11-22 11:54:43.943  
timestamp                                1700654083943074899  
body_list  [{'position': [-0.17799113690853102, 0.2396394...  

[2 rows x 349 columns]

In [124]:
# Dealing with nanosecond timestamps
from datetime import datetime, timedelta

startStamp = contents.iloc[:,0]["timestamp"]
stopStamp = contents.iloc[:,contents.shape[1]-1]["timestamp"]

print(startStamp)


start = datetime.fromtimestamp(startStamp/(1000**3))
stop = datetime.fromtimestamp(stopStamp/(1000**3))
print(start, "\n")
print(stopStamp)
print(stop)


1700654078059222899
2023-11-22 12:54:38.059223 

1700654083943074899
2023-11-22 12:54:43.943075


In [125]:
### Getting the damn seconds
print(stop-start)
print(type(stop-start))
print((stop-start).total_seconds())

0:00:05.883852
<class 'datetime.timedelta'>
5.883852


In [126]:
### Drop the empty body_list columns
for i in range(contents.shape[1]):
    if (i>=contents.shape[1]): 
        break
    if (not (contents.iloc[:,i]["body_list"])): 
        contents = contents.drop(contents.columns[i], axis=1)
display(contents)

# compute new start time
startStamp = contents.iloc[:,0]["timestamp"]
start = datetime.fromtimestamp(startStamp/(1000**3)) - timedelta(hours=1, minutes=0) # subtraction to convert to GMT

stopStamp = contents.iloc[:,contents.shape[1]-1]["timestamp"]
stop = datetime.fromtimestamp(stopStamp/(1000**3)) - timedelta(hours=1, minutes=0) # subtraction to convert to GMT



2023-11-22 11:54:38.159  \
timestamp                                1700654078159224899   
body_list  [{'position': [0.06269187480211201, 0.23638167...   

                                     2023-11-22 11:54:38.175  \
timestamp                                1700654078175975899   
body_list  [{'position': [0.061249434947967, 0.2368403375...   

                                     2023-11-22 11:54:38.192  \
timestamp                                1700654078192609899   
body_list  [{'position': [0.060380466282367005, 0.2371510...   

                                     2023-11-22 11:54:38.209  \
timestamp                                1700654078209228899   
body_list  [{'position': [0.059524856507778, 0.2371422499...   

                                     2023-11-22 11:54:38.225  \
timestamp                                1700654078225982899   
body_list  [{'position': [0.059154763817787004, 0.2367707...   

                                     2023-11-22 11:54:38.242  \
timestamp                                1700654078242618899   
body_list  [{'position': [0.060176365077495006, 0.2364491...   

                                     2023-11-22 11:54:38.259  \
timestamp                                1700654078259232899   
body_list  [{'position': [0.058992676436901, 0.2362396121...   

                                     2023-11-22 11:54:38.275  \
timestamp                                1700654078275982899   
body_list  [{'position': [0.060011230409145, 0.2360790520...   

                                     2023-11-22 11:54:38.292  \
timestamp                                1700654078292628899   
body_list  [{'position': [0.058555230498313, 0.2353321015...   

                                     2023-11-22 11:54:38.309  ...  \
timestamp                                1700654078309233899  ...   
body_list  [{'position': [0.058310367166996, 0.2361847609...  ...   

                                     2023-11-22 11:54:43.793  \
timestamp                                1700654083793089899   
body_list  [{'position': [-0.18967261910438502, 0.2430174...   

                                     2023-11-22 11:54:43.809  \
timestamp                                1700654083809814899   
body_list  [{'position': [-0.188304513692855, 0.242877885...   

                                     2023-11-22 11:54:43.826  \
timestamp                                1700654083826319899   
body_list  [{'position': [-0.18694186210632302, 0.2426286...   

                                     2023-11-22 11:54:43.843  \
timestamp                                1700654083843071899   
body_list  [{'position': [-0.18561515212059002, 0.2422894...   

                                     2023-11-22 11:54:43.859  \
timestamp                                1700654083859820899   
body_list  [{'position': [-0.184339731931686, 0.242005527...   

                                     2023-11-22 11:54:43.876  \
timestamp                                1700654083876371899   
body_list  [{'position': [-0.182976365089416, 0.241660505...   

                                     2023-11-22 11:54:43.893  \
timestamp                                1700654083893091899   
body_list  [{'position': [-0.18166434764862002, 0.2411778...   

                                     2023-11-22 11:54:43.909  \
timestamp                                1700654083909824899   
body_list  [{'position': [-0.180418908596038, 0.240578994...   

                                     2023-11-22 11:54:43.926  \
timestamp                                1700654083926324899   
body_list  [{'position': [-0.17917568981647403, 0.2401091...   

                                     2023-11-22 11:54:43.943  
timestamp                                1700654083943074899  
body_list  [{'position': [-0.17799113690853102, 0.2396394...  

[2 rows x 348 columns]

In [127]:
### Trying to create a method to breakdown data into half a second intervals 
## Create array
tm_wdw = 0.5
total_time = (stop-start).total_seconds()
print(total_time)
num_itr = int(total_time//tm_wdw)
intervals = []
measurments = []
prev_i=0

## Fill array
for i in range(contents.shape[1]): # iterate through columns
    column = contents.iloc[:,i]
    key_lst = column["body_list"][0]["keypoint"]
    timepoint = datetime.fromtimestamp(column["timestamp"]/(1000**3)) - timedelta(hours=1, minutes=0) # subtraction to convert to GMT
    intr_i = int((timepoint-start).total_seconds()//tm_wdw)
    if (prev_i==intr_i):
        measurments.append(key_lst)
    else:
        intervals.append(measurments)
        measurments=[]
    prev_i = intr_i

# check everything works afterwards
display("interv. num: {}".format(len(intervals)))   
sum = 0
for i in range(len(intervals)):
    print(len(intervals[i]))
    sum += (len(intervals[i]))
print("sum: ", sum)


5.78385


'interv. num: 11'

30
29
29
29
29
29
29
29
29
29
29
sum:  320


In [128]:
# Check whether my non-overlapping points hypothesise is correct
tmp = np.array(range(60))
print(tmp[1:len(tmp):23])
print(tmp[0:len(tmp):23])

[ 1 24 47]
[ 0 23 46]


In [129]:
# check if I can use single index
print(intervals[0:1])
print(len(np.array(intervals))) # unequal dimensions

[[[[0.00026744604110700003, 0.12050634622573801, -2.081075191497802], [0.021545166149735003, 0.28309279680252003, -2.020737171173095], [0.044085495173931004, 0.44564568996429405, -1.960768461227417], [0.066626504063606, 0.608203470706939, -1.900797963142395], [0.113815523684024, 0.605113565921783, -1.9073927402496331], [0.24365237355232203, 0.5941528677940361, -1.926483988761901], [0.296122938394546, 0.39882323145866305, -2.097994089126587], [0.34298354387283303, 0.15762405097484503, -2.166142225265503], [0.352355659008026, 0.109384216368198, -2.179771900177002], [0.37109988927841103, 0.012904547154903, -2.207031011581421], [0.301744937896728, 0.051606528460979004, -2.200889587402343], [0.019682472571730003, 0.6130601763725281, -1.8935513496398921], [-0.11015436798334101, 0.6240208745002741, -1.874460101127624], [-0.23199239373207, 0.442853808403015, -2.024980783462524], [-0.28418943285942, 0.19326926767826003, -2.024604320526123], [-0.294628828763961, 0.14335235953330902, -2.024528980

ValueError: setting an array element with a sequence. The requested array has an inhomogeneous shape after 1 dimensions. The detected shape was (11,) + inhomogeneous part.

In [ ]:
# Check how numpy append works
arr = np.concatenate((np.empty(), [1, 2, 3]), axis=0)
print(arr)
print(np.concatenate((arr, [4, 5, 6]), axis=0))


TypeError: empty() missing required argument 'shape' (pos 0)

In [ ]:
# Start with an empty array
result_array = np.empty((0, 3, 3))  # Assuming 3x3 arrays, you can adjust the shape as needed

# Create some sample 3x3 arrays
array1 = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
array2 = np.array([[10, 11, 12], [13, 14, 15], [16, 17, 18]])
array3 = np.array([[19, 20, 21], [22, 23, 24], [25, 26, 27]])

# Iterate and insert arrays into the result array
for arr in [array1, array2, array3]:
    result_array = np.concatenate((result_array, [arr]), axis=0)

print(result_array)

[[[ 1.  2.  3.]
  [ 4.  5.  6.]
  [ 7.  8.  9.]]

 [[10. 11. 12.]
  [13. 14. 15.]
  [16. 17. 18.]]

 [[19. 20. 21.]
  [22. 23. 24.]
  [25. 26. 27.]]]


In [130]:
# select 15 time points from a given interval of points
def selectTimePoints(slct_intrv, tm_pts_num):
    stp = round(len(slct_intrv) / tm_pts_num) # next extract relevant number (15 time points) of coordinates in relevant time intervals

    slct_idxs = list(range(0, len(slct_intrv), stp)) # range() in python 3 is an iterator object
    ##print(slct_idxs)
    unslct_idxs = list(range(1, len(slct_intrv), stp))
    ##print(unslct_idxs)
    missing = tm_pts_num-len(slct_idxs)
    missing = missing if missing>0 else 0  
    slct_idxs.extend(np.random.choice(unslct_idxs, missing, replace=False)) # add leftovers determined randomly
    slct_idxs.sort() # sort to ensure correct order when used as indexes
    ##print(slct_idxs)
    ##print()


    tmp_arr = np.array(slct_intrv) # array of skeletons in order
    key_points = tmp_arr[slct_idxs,:] # array of skeletons in a correct order # (row, element/column) 
    return key_points

In [131]:
import random as rnd

### Next take this broken down data and create an X and Y arrays
# X array:
#   Needs to contain 4*15*3 data points per line because 4 features * 15 different time points * 3 
#   coordinates per feature. Order: features, x, time-point 1 -> features, y, time-point 1 -> 
#   features, z, time-point 1 -> features, x, time-point 2 -> ... .
# Y array:
#   Similar fashion, but this time it is for output and not input.
X = []
Y = []


total_time = round((stop-start).total_seconds()) # convert to int
tm_pts_num = 15
slct_keys = [2, 7, 14, 26] # see stereolab 34 body point model
wdw_len = 4 # (4 slots 0.5 seconds each)

for i in range(len(intervals)-3): # how much windows do I get in this interval? -2 from the end, 
                                    # -1 from the beginning. Hence total -3.
    wdw_hlf_end = round((wdw_len/2)+i) # move the sliding window
    wdw_end = wdw_len+i 

    slct_intrv = []
    for in_i in range(i, wdw_hlf_end): # extract relevant time intervals
        slct_intrv.extend(intervals[in_i])
    in_skltns = selectTimePoints(slct_intrv, tm_pts_num)

    slct_intrv = [] # use same array, but clear it
    for out_i in range(wdw_hlf_end, wdw_end):
        slct_intrv.extend(intervals[out_i])
    out_skltns = selectTimePoints(slct_intrv, tm_pts_num)

    X.append(in_skltns) # 15 pts * 34 jnts * 3 crdnts in each row  # easier to append to standard arrays then to numpy
    Y.append(out_skltns) 

# check if dimensions are correct
if (True): 
    print(len(intervals)-3)
    print(len(X)) # this should be equal to value on the line above
    print(len(X[0])) # this should be 15
    print(len(X[0][0])) # this should be 34
    print(len(X[0][0][0])) # this should be 3

# check if same dimensions everywhere + convert to numpy
Xdata = np.array(X)
YData = np.array(Y)


8
8
15
34
3
