In [107]:
import pandas as pd
import numpy as np


In [108]:
### METHODS:

### MAIN:
# Tested on:
#   1. skCrateLeft1.json -> works (dimensions match)
#   2. skCupRight1.json -> works (dimensions match)
#   3. 

contents = pd.read_json("/Users/kirillgugunishvili/Documents/GitHub/Project3-1/Data/SkeletonData/skFloorRight.json")
print(type(contents))
print()
display(contents)

<class 'pandas.core.frame.DataFrame'>



2023-11-22 11:43:37.852 2023-11-22 11:43:37.935  \
timestamp     1700653417852704210     1700653417935958210   
body_list                      []                      []   

                                     2023-11-22 11:43:37.952  \
timestamp                                1700653417952729210   
body_list  [{'position': [-0.063974887132644, 0.046088576...   

                                     2023-11-22 11:43:37.969  \
timestamp                                1700653417969214210   
body_list  [{'position': [-0.06414320319890901, 0.0416457...   

                                     2023-11-22 11:43:37.985  \
timestamp                                1700653417985963210   
body_list  [{'position': [-0.064558118581771, 0.039302349...   

                                     2023-11-22 11:43:38.002  \
timestamp                                1700653418002732210   
body_list  [{'position': [-0.06495788693428, 0.0371291935...   

                                     2023-11-22 11:43:38.019  \
timestamp                                1700653418019338210   
body_list  [{'position': [-0.06510154902935, 0.0344705581...   

                                     2023-11-22 11:43:38.035  \
timestamp                                1700653418035963210   
body_list  [{'position': [-0.06538575887680001, 0.0325416...   

                                     2023-11-22 11:43:38.052  \
timestamp                                1700653418052714210   
body_list  [{'position': [-0.065585628151893, 0.031049311...   

                                     2023-11-22 11:43:38.069  ...  \
timestamp                                1700653418069341210  ...   
body_list  [{'position': [-0.06564262509346, 0.0285212397...  ...   

                                     2023-11-22 11:43:42.986  \
timestamp                                1700653422986410210   
body_list  [{'position': [-0.138357684016227, -0.08042263...   

                                     2023-11-22 11:43:43.003  \
timestamp                                1700653423003162210   
body_list  [{'position': [-0.137914940714836, -0.07965108...   

                                     2023-11-22 11:43:43.019  \
timestamp                                1700653423019656210   
body_list  [{'position': [-0.13743464648723602, -0.078907...   

                                     2023-11-22 11:43:43.036  \
timestamp                                1700653423036405210   
body_list  [{'position': [-0.13693885505199402, -0.078169...   

                                     2023-11-22 11:43:43.053  \
timestamp                                1700653423053165210   
body_list  [{'position': [-0.13655392825603402, -0.077732...   

                                     2023-11-22 11:43:43.069  \
timestamp                                1700653423069789210   
body_list  [{'position': [-0.136176869273185, -0.07736402...   

                                     2023-11-22 11:43:43.086  \
timestamp                                1700653423086403210   
body_list  [{'position': [-0.13578966259956302, -0.076942...   

                                     2023-11-22 11:43:43.103  \
timestamp                                1700653423103178210   
body_list  [{'position': [-0.135487556457519, -0.07651315...   

                                     2023-11-22 11:43:43.119  \
timestamp                                1700653423119781210   
body_list  [{'position': [-0.13519316911697302, -0.076089...   

                                     2023-11-22 11:43:43.136  
timestamp                                1700653423136409210  
body_list  [{'position': [-0.134962663054466, -0.07580730...  

[2 rows x 314 columns]

In [109]:
# Dealing with nanosecond timestamps
from datetime import datetime, timedelta

startStamp = contents.iloc[:,0]["timestamp"]
stopStamp = contents.iloc[:,contents.shape[1]-1]["timestamp"]

print(startStamp)


start = datetime.fromtimestamp(startStamp/(1000**3))
stop = datetime.fromtimestamp(stopStamp/(1000**3))
print(start, "\n")
print(stopStamp)
print(stop)


1700653417852704210
2023-11-22 12:43:37.852704 

1700653423136409210
2023-11-22 12:43:43.136409


In [110]:
### Getting the damn seconds
print(stop-start)
print(type(stop-start))
print((stop-start).total_seconds())

0:00:05.283705
<class 'datetime.timedelta'>
5.283705


In [113]:
### Drop the empty body_list columns
for i in range(contents.shape[1]):
    if (i>=contents.shape[1]): 
        break
    if (not (contents.iloc[:,i]["body_list"])): 
        contents = contents.drop(contents.columns[i], axis=1)
display(contents)

# compute new start time
startStamp = contents.iloc[:,0]["timestamp"]
start = datetime.fromtimestamp(startStamp/(1000**3)) - timedelta(hours=1, minutes=0) # subtraction to convert to GMT

stopStamp = contents.iloc[:,contents.shape[1]-1]["timestamp"]
stop = datetime.fromtimestamp(stopStamp/(1000**3)) - timedelta(hours=1, minutes=0) # subtraction to convert to GMT



2023-11-22 11:43:37.952  \
timestamp                                1700653417952729210   
body_list  [{'position': [-0.063974887132644, 0.046088576...   

                                     2023-11-22 11:43:37.969  \
timestamp                                1700653417969214210   
body_list  [{'position': [-0.06414320319890901, 0.0416457...   

                                     2023-11-22 11:43:37.985  \
timestamp                                1700653417985963210   
body_list  [{'position': [-0.064558118581771, 0.039302349...   

                                     2023-11-22 11:43:38.002  \
timestamp                                1700653418002732210   
body_list  [{'position': [-0.06495788693428, 0.0371291935...   

                                     2023-11-22 11:43:38.019  \
timestamp                                1700653418019338210   
body_list  [{'position': [-0.06510154902935, 0.0344705581...   

                                     2023-11-22 11:43:38.035  \
timestamp                                1700653418035963210   
body_list  [{'position': [-0.06538575887680001, 0.0325416...   

                                     2023-11-22 11:43:38.052  \
timestamp                                1700653418052714210   
body_list  [{'position': [-0.065585628151893, 0.031049311...   

                                     2023-11-22 11:43:38.069  \
timestamp                                1700653418069341210   
body_list  [{'position': [-0.06564262509346, 0.0285212397...   

                                     2023-11-22 11:43:38.085  \
timestamp                                1700653418085969210   
body_list  [{'position': [-0.06578420102596201, 0.0264291...   

                                     2023-11-22 11:43:38.102  ...  \
timestamp                                1700653418102751210  ...   
body_list  [{'position': [-0.06597634404897601, 0.0238475...  ...   

                                     2023-11-22 11:43:42.986  \
timestamp                                1700653422986410210   
body_list  [{'position': [-0.138357684016227, -0.08042263...   

                                     2023-11-22 11:43:43.003  \
timestamp                                1700653423003162210   
body_list  [{'position': [-0.137914940714836, -0.07965108...   

                                     2023-11-22 11:43:43.019  \
timestamp                                1700653423019656210   
body_list  [{'position': [-0.13743464648723602, -0.078907...   

                                     2023-11-22 11:43:43.036  \
timestamp                                1700653423036405210   
body_list  [{'position': [-0.13693885505199402, -0.078169...   

                                     2023-11-22 11:43:43.053  \
timestamp                                1700653423053165210   
body_list  [{'position': [-0.13655392825603402, -0.077732...   

                                     2023-11-22 11:43:43.069  \
timestamp                                1700653423069789210   
body_list  [{'position': [-0.136176869273185, -0.07736402...   

                                     2023-11-22 11:43:43.086  \
timestamp                                1700653423086403210   
body_list  [{'position': [-0.13578966259956302, -0.076942...   

                                     2023-11-22 11:43:43.103  \
timestamp                                1700653423103178210   
body_list  [{'position': [-0.135487556457519, -0.07651315...   

                                     2023-11-22 11:43:43.119  \
timestamp                                1700653423119781210   
body_list  [{'position': [-0.13519316911697302, -0.076089...   

                                     2023-11-22 11:43:43.136  
timestamp                                1700653423136409210  
body_list  [{'position': [-0.134962663054466, -0.07580730...  

[2 rows x 312 columns]

In [114]:
### Trying to create a method to breakdown data into half a second intervals 
## Create array
tm_wdw = 0.5
total_time = (stop-start).total_seconds()
print(total_time)
num_itr = int(total_time//tm_wdw)
intervals = []
measurments = []
prev_i=0

## Fill array
for i in range(contents.shape[1]): # iterate through columns
    column = contents.iloc[:,i]
    key_lst = column["body_list"][0]["keypoint"]
    timepoint = datetime.fromtimestamp(column["timestamp"]/(1000**3)) - timedelta(hours=1, minutes=0) # subtraction to convert to GMT
    intr_i = int((timepoint-start).total_seconds()//tm_wdw)
    if (prev_i==intr_i):
        measurments.append(key_lst)
    else:
        intervals.append(measurments)
        measurments=[]
    prev_i = intr_i

# check everything works afterwards
display("interv. num: {}".format(len(intervals)))   
sum = 0
for i in range(len(intervals)):
    print(len(intervals[i]))
    sum += (len(intervals[i]))
print("sum: ", sum)


5.18368


'interv. num: 10'

31
28
29
29
29
29
29
29
29
29
sum:  291


In [115]:
# Check whether my non-overlapping points hypothesise is correct
tmp = np.array(range(60))
print(tmp[1:len(tmp):23])
print(tmp[0:len(tmp):23])

[ 1 24 47]
[ 0 23 46]


In [116]:
# check if I can use single index
print(intervals[0:1])
print(len(np.array(intervals))) # unequal dimensions

[[[[-0.10068511962890601, -0.15508630871772702, -1.969599723815918], [-0.088272362947463, 0.01639337837696, -1.9555857181549072], [-0.075097106397151, 0.18780188262462602, -1.9413977861404421], [-0.061921454966068004, 0.35921549797058105, -1.927209496498108], [-0.015047952532768001, 0.35692444443702703, -1.931660652160644], [0.11541925370693201, 0.34794098138809204, -1.944283843040466], [0.16502110660076102, 0.12222437560558301, -2.084224700927734], [0.211643949151039, -0.11816991865634902, -2.170953512191772], [0.220968514680862, -0.16624876856803802, -2.188299179077148], [0.239617645740509, -0.262406468391418, -2.222990751266479], [0.169006019830703, -0.22401222586631703, -2.211747407913208], [-0.10865175724029501, 0.363369643688201, -1.9226040840148921], [-0.239118963479995, 0.372353106737136, -1.90998089313507], [-0.337405979633331, 0.14795702695846502, -2.023901224136352], [-0.39517626166343606, -0.10531166195869401, -2.02550458908081], [-0.40673032402992204, -0.155965402722358, -

ValueError: setting an array element with a sequence. The requested array has an inhomogeneous shape after 1 dimensions. The detected shape was (10,) + inhomogeneous part.

In [117]:
# Check how numpy append works
arr = np.concatenate((np.empty(), [1, 2, 3]), axis=0)
print(arr)
print(np.concatenate((arr, [4, 5, 6]), axis=0))


TypeError: empty() missing required argument 'shape' (pos 0)

In [118]:
# Start with an empty array
result_array = np.empty((0, 3, 3))  # Assuming 3x3 arrays, you can adjust the shape as needed

# Create some sample 3x3 arrays
array1 = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
array2 = np.array([[10, 11, 12], [13, 14, 15], [16, 17, 18]])
array3 = np.array([[19, 20, 21], [22, 23, 24], [25, 26, 27]])

# Iterate and insert arrays into the result array
for arr in [array1, array2, array3]:
    result_array = np.concatenate((result_array, [arr]), axis=0)

print(result_array)

[[[ 1.  2.  3.]
  [ 4.  5.  6.]
  [ 7.  8.  9.]]

 [[10. 11. 12.]
  [13. 14. 15.]
  [16. 17. 18.]]

 [[19. 20. 21.]
  [22. 23. 24.]
  [25. 26. 27.]]]


In [119]:
# select 15 time points from a given interval of points
def selectTimePoints(slct_intrv, tm_pts_num):
    stp = round(len(slct_intrv) / tm_pts_num) # next extract relevant number (15 time points) of coordinates in relevant time intervals

    slct_idxs = list(range(0, len(slct_intrv), stp)) # range() in python 3 is an iterator object
    ##print(slct_idxs)
    unslct_idxs = list(range(1, len(slct_intrv), stp))
    ##print(unslct_idxs)
    missing = tm_pts_num-len(slct_idxs)
    missing = missing if missing>0 else 0  
    slct_idxs.extend(np.random.choice(unslct_idxs, missing, replace=False)) # add leftovers determined randomly
    slct_idxs.sort() # sort to ensure correct order when used as indexes
    ##print(slct_idxs)
    ##print()


    tmp_arr = np.array(slct_intrv) # array of skeletons in order
    key_points = tmp_arr[slct_idxs,:] # array of skeletons in a correct order # (row, element/column) 
    return key_points

In [121]:
import random as rnd

### Next take this broken down data and create an X and Y arrays
# X array:
#   Needs to contain 4*15*3 data points per line because 4 features * 15 different time points * 3 
#   coordinates per feature. Order: features, x, time-point 1 -> features, y, time-point 1 -> 
#   features, z, time-point 1 -> features, x, time-point 2 -> ... .
# Y array:
#   Similar fashion, but this time it is for output and not input.
X = []
Y = []


total_time = round((stop-start).total_seconds()) # convert to int
tm_pts_num = 15
slct_keys = [2, 7, 14, 26] # see stereolab 34 body point model
wdw_len = 4 # (4 slots 0.5 seconds each)

for i in range(len(intervals)-3): # how much windows do I get in this interval? -2 from the end, 
                                    # -1 from the beginning. Hence total -3.
    wdw_hlf_end = round((wdw_len/2)+i) # move the sliding window
    wdw_end = wdw_len+i 

    slct_intrv = []
    for in_i in range(i, wdw_hlf_end): # extract relevant time intervals
        slct_intrv.extend(intervals[in_i])
    in_skltns = selectTimePoints(slct_intrv, tm_pts_num)

    slct_intrv = [] # use same array, but clear it
    for out_i in range(wdw_hlf_end, wdw_end):
        slct_intrv.extend(intervals[out_i])
    out_skltns = selectTimePoints(slct_intrv, tm_pts_num)

    X.append(in_skltns) # 15 pts * 34 jnts * 3 crdnts in each row  # easier to append to standard arrays then to numpy
    Y.append(out_skltns) 

# check if dimensions are correct
if (True): 
    print(len(intervals)-3)
    print(len(X)) # this should be equal to value on the line above
    print(len(X[0])) # this should be 15
    print(len(X[0][0])) # this should be 34
    print(len(X[0][0][0])) # this should be 3



7
7
15
34
3
