In [1]:
import pandas as pd
import numpy as np


In [2]:
### METHODS:

### MAIN:
# Tested on:
#   1. skCrateLeft1.json -> works (dimensions match)
#   2. skCupRight1.json -> works (dimensions match)
#   3. skFloorRight.json -> works (dimension match + dimension same/numpy conversion)

contents = pd.read_json("/Users/kirillgugunishvili/Documents/GitHub/Project3-1/Data/SkeletonData/skCrateLeft1.json")
print(type(contents))
print()
display(contents)

display(contents.iloc[:,0])

<class 'pandas.core.frame.DataFrame'>



2023-11-22 11:38:42.060 2023-11-22 11:38:42.143  \
timestamp     1700653122060147649     1700653122143532649   
body_list                      []                      []   

                                     2023-11-22 11:38:42.160  \
timestamp                                1700653122160161649   
body_list  [{'position': [0.113704234361648, -0.025178760...   

                                     2023-11-22 11:38:42.176  \
timestamp                                1700653122176913649   
body_list  [{'position': [0.11352799832820801, -0.0292186...   

                                     2023-11-22 11:38:42.193  \
timestamp                                1700653122193535649   
body_list  [{'position': [0.11294084787368701, -0.0339553...   

                                     2023-11-22 11:38:42.210  \
timestamp                                1700653122210165649   
body_list  [{'position': [0.11243174225091901, -0.0376108...   

                                     2023-11-22 11:38:42.226  \
timestamp                                1700653122226925649   
body_list  [{'position': [0.11239656805992101, -0.0409383...   

                                     2023-11-22 11:38:42.243  \
timestamp                                1700653122243568649   
body_list  [{'position': [0.11247570812702101, -0.0443702...   

                                     2023-11-22 11:38:42.260  \
timestamp                                1700653122260326649   
body_list  [{'position': [0.11242754012346201, -0.0473631...   

                                     2023-11-22 11:38:42.276  ...  \
timestamp                                1700653122276820649  ...   
body_list  [{'position': [0.11231756210327101, -0.0508978...  ...   

                                     2023-11-22 11:38:47.343  \
timestamp                                1700653127343978649   
body_list  [{'position': [0.159868389368057, -0.087202966...   

                                     2023-11-22 11:38:47.360  \
timestamp                                1700653127360725649   
body_list  [{'position': [0.15898013114929202, -0.0867106...   

                                     2023-11-22 11:38:47.377  \
timestamp                                1700653127377228649   
body_list  [{'position': [0.15780311822891202, -0.0860883...   

                                     2023-11-22 11:38:47.393  \
timestamp                                1700653127393981649   
body_list  [{'position': [0.156516283750534, -0.085650593...   

                                     2023-11-22 11:38:47.410  \
timestamp                                1700653127410730649   
body_list  [{'position': [0.15522357821464502, -0.0853744...   

                                     2023-11-22 11:38:47.427  \
timestamp                                1700653127427243649   
body_list  [{'position': [0.154173791408538, -0.084838211...   

                                     2023-11-22 11:38:47.444  \
timestamp                                1700653127444016649   
body_list  [{'position': [0.15336142480373302, -0.0843776...   

                                     2023-11-22 11:38:47.460  \
timestamp                                1700653127460766649   
body_list  [{'position': [0.152460992336273, -0.083913072...   

                                     2023-11-22 11:38:47.477  \
timestamp                                1700653127477266649   
body_list  [{'position': [0.151038318872451, -0.083447650...   

                                     2023-11-22 11:38:47.493  
timestamp                                1700653127493983649  
body_list  [{'position': [0.15027017891407002, -0.0835500...  

[2 rows x 323 columns]

timestamp    1700653122060147649
body_list                     []
Name: 2023-11-22 11:38:42.060000, dtype: object

In [3]:
# Dealing with nanosecond timestamps
from datetime import datetime, timedelta

startStamp = contents.iloc[:,0]["timestamp"]
stopStamp = contents.iloc[:,contents.shape[1]-1]["timestamp"]

print(startStamp)


start = datetime.fromtimestamp(startStamp/(1000**3))
stop = datetime.fromtimestamp(stopStamp/(1000**3))
print(start, "\n")
print(stopStamp)
print(stop)


1700653122060147649
2023-11-22 12:38:42.060148 

1700653127493983649
2023-11-22 12:38:47.493984


In [4]:
### Getting the damn seconds
print(stop-start)
print(type(stop-start))
print((stop-start).total_seconds())

0:00:05.433836
<class 'datetime.timedelta'>
5.433836


In [5]:
### Drop the empty body_list columns

## iterate and identify the drop names for columns
dropNames = []
for columnName, columnData in contents.items():
    if (not (columnData["body_list"])): 
        dropNames.extend([columnName])
contents = contents.drop(columns=dropNames)
display(contents)

# compute new start time
startStamp = contents.iloc[:,0]["timestamp"]
start = datetime.fromtimestamp(startStamp/(1000**3)) - timedelta(hours=1, minutes=0) # subtraction to convert to GMT

stopStamp = contents.iloc[:,contents.shape[1]-1]["timestamp"]
stop = datetime.fromtimestamp(stopStamp/(1000**3)) - timedelta(hours=1, minutes=0) # subtraction to convert to GMT



2023-11-22 11:38:42.160  \
timestamp                                1700653122160161649   
body_list  [{'position': [0.113704234361648, -0.025178760...   

                                     2023-11-22 11:38:42.176  \
timestamp                                1700653122176913649   
body_list  [{'position': [0.11352799832820801, -0.0292186...   

                                     2023-11-22 11:38:42.193  \
timestamp                                1700653122193535649   
body_list  [{'position': [0.11294084787368701, -0.0339553...   

                                     2023-11-22 11:38:42.210  \
timestamp                                1700653122210165649   
body_list  [{'position': [0.11243174225091901, -0.0376108...   

                                     2023-11-22 11:38:42.226  \
timestamp                                1700653122226925649   
body_list  [{'position': [0.11239656805992101, -0.0409383...   

                                     2023-11-22 11:38:42.243  \
timestamp                                1700653122243568649   
body_list  [{'position': [0.11247570812702101, -0.0443702...   

                                     2023-11-22 11:38:42.260  \
timestamp                                1700653122260326649   
body_list  [{'position': [0.11242754012346201, -0.0473631...   

                                     2023-11-22 11:38:42.276  \
timestamp                                1700653122276820649   
body_list  [{'position': [0.11231756210327101, -0.0508978...   

                                     2023-11-22 11:38:42.293  \
timestamp                                1700653122293539649   
body_list  [{'position': [0.11186785995960201, -0.0531359...   

                                     2023-11-22 11:38:42.310  ...  \
timestamp                                1700653122310287649  ...   
body_list  [{'position': [0.111508637666702, -0.055972993...  ...   

                                     2023-11-22 11:38:47.343  \
timestamp                                1700653127343978649   
body_list  [{'position': [0.159868389368057, -0.087202966...   

                                     2023-11-22 11:38:47.360  \
timestamp                                1700653127360725649   
body_list  [{'position': [0.15898013114929202, -0.0867106...   

                                     2023-11-22 11:38:47.377  \
timestamp                                1700653127377228649   
body_list  [{'position': [0.15780311822891202, -0.0860883...   

                                     2023-11-22 11:38:47.393  \
timestamp                                1700653127393981649   
body_list  [{'position': [0.156516283750534, -0.085650593...   

                                     2023-11-22 11:38:47.410  \
timestamp                                1700653127410730649   
body_list  [{'position': [0.15522357821464502, -0.0853744...   

                                     2023-11-22 11:38:47.427  \
timestamp                                1700653127427243649   
body_list  [{'position': [0.154173791408538, -0.084838211...   

                                     2023-11-22 11:38:47.444  \
timestamp                                1700653127444016649   
body_list  [{'position': [0.15336142480373302, -0.0843776...   

                                     2023-11-22 11:38:47.460  \
timestamp                                1700653127460766649   
body_list  [{'position': [0.152460992336273, -0.083913072...   

                                     2023-11-22 11:38:47.477  \
timestamp                                1700653127477266649   
body_list  [{'position': [0.151038318872451, -0.083447650...   

                                     2023-11-22 11:38:47.493  
timestamp                                1700653127493983649  
body_list  [{'position': [0.15027017891407002, -0.0835500...  

[2 rows x 321 columns]

In [6]:
### Trying to create a method to breakdown data into half a second intervals 
## Create array
tm_wdw = 0.5
total_time = (stop-start).total_seconds()
print(total_time)
num_itr = int(total_time//tm_wdw)
intervals = []
measurments = []
prev_i=0

## Fill array
for i in range(contents.shape[1]): # iterate through columns
    column = contents.iloc[:,i]
    key_lst = column["body_list"][0]["keypoint"]
    timepoint = datetime.fromtimestamp(column["timestamp"]/(1000**3)) - timedelta(hours=1, minutes=0) # subtraction to convert to GMT
    intr_i = int((timepoint-start).total_seconds()//tm_wdw)
    if (prev_i==intr_i):
        measurments.append(key_lst)
    else:
        intervals.append(measurments)
        measurments=[]
    prev_i = intr_i

# check everything works afterwards
display("interv. num: {}".format(len(intervals)))   
sum = 0
for i in range(len(intervals)):
    print(len(intervals[i]))
    sum += (len(intervals[i]))
print("sum: ", sum)


5.333822


'interv. num: 10'

30
29
29
29
29
29
29
29
29
29
sum:  291


In [7]:
# Check whether my non-overlapping points hypothesise is correct
tmp = np.array(range(60))
print(tmp[1:len(tmp):23])
print(tmp[0:len(tmp):23])

[ 1 24 47]
[ 0 23 46]


In [8]:
# check if I can use single index
print(intervals[0:1])
print(len(np.array(intervals))) # unequal dimensions

[[[[0.07437327504158, -0.215841740369796, -1.947480201721191], [0.08289800584316201, -0.038061156868934, -1.907608032226562], [0.09479571878910001, 0.13942165672779, -1.8672757148742671], [0.10669378191232601, 0.316909790039062, -1.8269422054290771], [0.15642777085304202, 0.31416779756546004, -1.825064539909362], [0.288128525018692, 0.30433976650238004, -1.820666909217834], [0.33556756377220104, 0.065431654453277, -1.941143035888671], [0.36629322171211204, -0.19110533595085102, -1.980076670646667], [0.37243834137916504, -0.242412731051445, -1.987863421440124], [0.38472861051559404, -0.345027536153793, -2.003436803817749], [0.31759837269783003, -0.298955559730529, -2.009281873703003], [0.057089105248451004, 0.32158082723617504, -1.828381538391113], [-0.074611648917198, 0.33140885829925504, -1.8327791690826412], [-0.154495596885681, 0.09871506690979001, -1.9481662511825562], [-0.203140795230865, -0.157864451408386, -1.939698576927185], [-0.21286983788013403, -0.209180355072021, -1.938005

ValueError: setting an array element with a sequence. The requested array has an inhomogeneous shape after 1 dimensions. The detected shape was (10,) + inhomogeneous part.

In [ ]:
# Check how numpy append works
arr = np.concatenate((np.empty(), [1, 2, 3]), axis=0)
print(arr)
print(np.concatenate((arr, [4, 5, 6]), axis=0))


TypeError: empty() missing required argument 'shape' (pos 0)

In [9]:
# Start with an empty array
result_array = np.empty((0, 3, 3))  # Assuming 3x3 arrays, you can adjust the shape as needed

# Create some sample 3x3 arrays
array1 = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
array2 = np.array([[10, 11, 12], [13, 14, 15], [16, 17, 18]])
array3 = np.array([[19, 20, 21], [22, 23, 24], [25, 26, 27]])

# Iterate and insert arrays into the result array
for arr in [array1, array2, array3]:
    result_array = np.concatenate((result_array, [arr]), axis=0)

print(result_array)

[[[ 1.  2.  3.]
  [ 4.  5.  6.]
  [ 7.  8.  9.]]

 [[10. 11. 12.]
  [13. 14. 15.]
  [16. 17. 18.]]

 [[19. 20. 21.]
  [22. 23. 24.]
  [25. 26. 27.]]]


In [10]:
# select 15 time points from a given interval of points
def selectTimePoints(slct_intrv, tm_pts_num):
    stp = round(len(slct_intrv) / tm_pts_num) # next extract relevant number (15 time points) of coordinates in relevant time intervals

    slct_idxs = list(range(0, len(slct_intrv), stp)) # range() in python 3 is an iterator object
    ##print(slct_idxs)
    unslct_idxs = list(range(1, len(slct_intrv), stp))
    ##print(unslct_idxs)
    missing = tm_pts_num-len(slct_idxs)
    missing = missing if missing>0 else 0  
    slct_idxs.extend(np.random.choice(unslct_idxs, missing, replace=False)) # add leftovers determined randomly
    slct_idxs.sort() # sort to ensure correct order when used as indexes
    ##print(slct_idxs)
    ##print()


    tmp_arr = np.array(slct_intrv) # array of skeletons in order
    key_points = tmp_arr[slct_idxs,:] # array of skeletons in a correct order # (row, element/column) 
    return key_points

In [13]:
import random as rnd

### Next take this broken down data and create an X and Y arrays
# X array:
#   Needs to contain 4*15*3 data points per line because 4 features * 15 different time points * 3 
#   coordinates per feature. Order: features, x, time-point 1 -> features, y, time-point 1 -> 
#   features, z, time-point 1 -> features, x, time-point 2 -> ... .
# Y array:
#   Similar fashion, but this time it is for output and not input.
X = []
Y = []


total_time = round((stop-start).total_seconds()) # convert to int
tm_pts_num = 15
slct_keys = [2, 7, 14, 26] # see stereolab 34 body point model
wdw_len = 4 # (4 slots 0.5 seconds each)

for i in range(len(intervals)-3): # how much windows do I get in this interval? -2 from the end, 
                                    # -1 from the beginning. Hence total -3.
    wdw_hlf_end = round((wdw_len/2)+i) # move the sliding window
    wdw_end = wdw_len+i 

    slct_intrv = []
    for in_i in range(i, wdw_hlf_end): # extract relevant time intervals
        slct_intrv.extend(intervals[in_i])
    in_skltns = selectTimePoints(slct_intrv, tm_pts_num)

    slct_intrv = [] # use same array, but clear it
    for out_i in range(wdw_hlf_end, wdw_end):
        slct_intrv.extend(intervals[out_i])
    out_skltns = selectTimePoints(slct_intrv, tm_pts_num)

    X.append(in_skltns) # 15 pts * 34 jnts * 3 crdnts in each row  # easier to append to standard arrays then to numpy
    Y.append(out_skltns) 

# check if dimensions are correct
if (True): 
    print(len(intervals)-3)
    print(len(X)) # this should be equal to value on the line above
    print(len(X[0])) # this should be 15
    print(len(X[0][0])) # this should be 34
    print(len(X[0][0][0])) # this should be 3
    print()

    print(len(intervals)-3)
    print(len(Y)) # this should be equal to value on the line above
    print(len(Y[0])) # this should be 15
    print(len(Y[0][0])) # this should be 34
    print(len(Y[0][0][0])) # this should be 3

# check if same dimensions everywhere + convert to numpy
Xdata = np.array(X)
YData = np.array(Y)


7
7
15
34
3

7
7
15
34
3


In [15]:
# How should I unravel this data?
display(X)
print()
display(X[0]) # too large of an output to determine anything

[array([[[ 0.07437328, -0.21584174, -1.9474802 ],
         [ 0.08289801, -0.03806116, -1.90760803],
         [ 0.09479572,  0.13942166, -1.86727571],
         ...,
         [ 0.05533463,  0.50374246, -1.80987537],
         [ 0.20708612, -0.94899762, -2.09507871],
         [-0.12808564, -0.90944499, -2.24236012]],
 
        [[ 0.07413611, -0.21376824, -1.95471418],
         [ 0.08278357, -0.03657094, -1.91233087],
         [ 0.09454891,  0.14036469, -1.86960661],
         ...,
         [ 0.05554476,  0.50405365, -1.807307  ],
         [ 0.20034552, -0.95128661, -2.10197711],
         [-0.13754486, -0.90562224, -2.25430107]],
 
        [[ 0.07345559, -0.21558994, -1.94940102],
         [ 0.08219357, -0.03759992, -1.91047466],
         [ 0.09442371,  0.14005104, -1.87094474],
         ...,
         [ 0.0541597 ,  0.50451308, -1.81790698],
         [ 0.19722995, -0.95204902, -2.08347201],
         [-0.13527238, -0.91082639, -2.24347711]],
 
        ...,
 
        [[ 0.05150565, -0.21640468

array([[[ 0.07437328, -0.21584174, -1.9474802 ],
        [ 0.08289801, -0.03806116, -1.90760803],
        [ 0.09479572,  0.13942166, -1.86727571],
        ...,
        [ 0.05533463,  0.50374246, -1.80987537],
        [ 0.20708612, -0.94899762, -2.09507871],
        [-0.12808564, -0.90944499, -2.24236012]],

       [[ 0.07413611, -0.21376824, -1.95471418],
        [ 0.08278357, -0.03657094, -1.91233087],
        [ 0.09454891,  0.14036469, -1.86960661],
        ...,
        [ 0.05554476,  0.50405365, -1.807307  ],
        [ 0.20034552, -0.95128661, -2.10197711],
        [-0.13754486, -0.90562224, -2.25430107]],

       [[ 0.07345559, -0.21558994, -1.94940102],
        [ 0.08219357, -0.03759992, -1.91047466],
        [ 0.09442371,  0.14005104, -1.87094474],
        ...,
        [ 0.0541597 ,  0.50451308, -1.81790698],
        [ 0.19722995, -0.95204902, -2.08347201],
        [-0.13527238, -0.91082639, -2.24347711]],

       ...,

       [[ 0.05150565, -0.21640468, -1.97487497],
        [ 0

In [16]:
# Try same things as last code block, but with smaller outputs
import torch
from torch import nn
from model import ED_Network


display(X[0][0][0])

array([ 0.07437328, -0.21584174, -1.9474802 ])

In [ ]:
>>> input = torch.randn(32, 1, 5, 5)
>>> # With default parameters
>>> m = nn.Flatten()
>>> output = m(input)
>>> output.size()
torch.Size([32, 25])
>>> # With non-default parameters
>>> m = nn.Flatten(0, 2)
>>> output = m(input)
>>> output.size()