In [1]:
import numpy as np

In [5]:
# Checking whether an array can be subtracted
x1 = np.arange(9.0).reshape((3, 3))
x2 = np.array([2.0,2.0,2.0])
display(x1)
display(x2)
display(np.subtract(x1, x2))

array([[0., 1., 2.],
       [3., 4., 5.],
       [6., 7., 8.]])

array([2., 2., 2.])

array([[-2., -1.,  0.],
       [ 1.,  2.,  3.],
       [ 4.,  5.,  6.]])