In [1]:
import numpy as np

In [2]:
# Checking whether an array can be subtracted
x1 = np.arange(9.0).reshape((3, 3))
x2 = np.array([2.0,2.0,2.0])
display(x1)
display(x2)
display(np.subtract(x1, x2))

array([[0., 1., 2.],
       [3., 4., 5.],
       [6., 7., 8.]])

array([2., 2., 2.])

array([[-2., -1.,  0.],
       [ 1.,  2.,  3.],
       [ 4.,  5.,  6.]])

In [5]:
x1 = np.arange(9.0).reshape((3, 3))
x2 = np.arange(9.0).reshape((3, 3))
display(x1)
display(x2)
display(np.divide(x1, x2))

array([[0., 1., 2.],
       [3., 4., 5.],
       [6., 7., 8.]])

array([[0., 1., 2.],
       [3., 4., 5.],
       [6., 7., 8.]])

/var/folders/vt/47mxbcvj5rd7mmyk053h49m00000gn/T/ipykernel_56114/2688880395.py:5: RuntimeWarning: invalid value encountered in divide
  display(np.divide(x1, x2))


array([[nan,  1.,  1.],
       [ 1.,  1.,  1.],
       [ 1.,  1.,  1.]])